### ISSUE TITLE
dataset release

### ISSUE THREAD

**Issue by NonvolatileMemory** [RUCAIBox/Slow_Thinking_with_LLMs#2]
Hi,

Thanks for your great work, will you release the 3.7k data you collected?

**Comment by byhteng** [comment]
same question

**Comment by waltonfuture** [comment]
same question

**Comment by xiaolizh1** [comment]
same question

**Comment by EliverQ** [comment]
Hi, guys! Thank you for your attention. We have open-sourced our training data at [here](https://github.com/RUCAIBox/Slow_Thinking_with_LLMs/tree/main/data).

**Comment by NonvolatileMemory** [comment]
thanks!
