### ISSUE TITLE
Request for Test Code to Reproduce Results

### ISSUE THREAD

**Issue by Freder-chen** [RUCAIBox/Slow_Thinking_with_LLMs#7]
Hello, 

Thank you for sharing your work. Could you please provide the test code for the related dataset? I would like to reproduce the results. 

Thank you!

**Comment by EliverQ** [comment]
Hello,

Thank you for reaching out. We have been following the evaluation code for [Qwen-2.5-Math](https://github.com/QwenLM/Qwen2.5-Math), which you might find useful if you're looking for something immediately. Our evaluation code will be organized and released soon.

Thank you for your attention!
